### PR TITLE
Use selfadjointView when computing eigenvectors

### PR DESCRIPTION
**Pull request by lisitsyn**
- Fixes wrong PCA results with dense eigensolver (thanks William Curram
  for reporting!)

### CODE REVIEW

**Comment by lisitsyn** [comment]
@iglesias want to take a look? ;)

**Comment by iglesias** [comment]
I don't have context on this one but I say, sure and go ahead.

**Comment by lisitsyn** [comment]
@iglesias there was an issue: when computing PCA with arpack we have all good. But when it comes to 'dense' eigenmethod which is just eigen3 thing, eigenvectors are like (0 0 0 0 1 0). I took a look and apparently we use selfadjoint view when computing covariance, thus resulting in a upper triangular matrix. With the fix it treats this matrix as a self adjoint, ignoring the lower triangular part (but diagonal).

**Comment by iglesias** [comment]
Ok, thanks for the explanation!

**Pull request merged**
