### PR TITLE
Add Findfmt.cmake like FindFeast.cmake.

### PR DESCRIPTION
**Pull request by iglesias**

### CODE REVIEW

**Comment by lisitsyn** [comment]
I am a bit confused. What is the platform you're fixing with custom Find Cmake?

**Comment by iglesias** [comment]
> I am a bit confused. What is the platform you're fixing with custom Find Cmake?

Sorry for the noise, I overlooked and should have made it draft. It's not ready yet.

About the platform, this change came up while working on cygwin for the mingw issue. With this "it helps" providing a direct error message of fmt missing, but it does not work yet in the most important path when it is available :)

I am not 100% sure I will be pushing it again tomorrow already, but during this week for sure.

**Comment by lisitsyn** [comment]
Got it!

**Comment by iglesias** [comment]
Found the button now to change it to draft even after it's opened, didn't see it before so thought it wasn't possible. So, thanks for the message after all :-D

**Comment by iglesias** [comment]
Ah, what I tried here with cmake is looking for the library, whereas I think fmt is being used header-only. It can be kept as it was, the direct error message if fmt is probably not worth. Sorry for the confusion.

**Pull request closed without merging**
